### PR TITLE
Add temporary script for Google Analytics4

### PR DESCRIPTION
**Pull request by Baggerone**

### CODE REVIEW

**Review by jason-jackson — COMMENTED** [review]
If both Universal analytics and GA4 are given, do we want to send both, or just one?

**Comment by Baggerone** [comment]
> If both Universal analytics and GA4 are given, do we want to send both, or just one?

For now, both until a bunch of GA4 data is built up.

**Review by mtompset — CHANGES_REQUESTED** [review]
https://developers.google.com/analytics/devguides/migration/measurement/add-ga4?technology=analyticsjs

I think you don't need as much code as you have. Read the above page.

**Comment by Baggerone** [comment]
> I think you don't need as much code as you have. Read the above page.
@mtompset 
I think it is simpler to manage if we just leave the old code in place temporarily and then delete it all in one block at the right time.  With both values being optional, it will be tricky getting all the `if` statements just right in trying to just have one set of script tags.

**Review by Schparky — APPROVED** [review]
I'm fine with the overlapping approach, but I wonder if we really use the analytics data enough to worry about it. What harm would there be in making a hard switch?

**Pull request closed without merging**
